apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: traincloud-dev
  labels:
    app: email
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP  # or omit 'type' since ClusterIP is default
  selector:
    app: email
  ports:
    - protocol: TCP
      name: email
      targetPort: 8081  # Container-Port
      port: 8081        # Cluster-intern
    - protocol: TCP
      name: health
      targetPort: 8080
      port: 8080       
    - protocol: TCP
      name: metrics
      targetPort: 9090
      port: 9090   